//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::email_verification::Entity as EmailVerification;
pub use super::profile::Entity as Profile;
pub use super::user::Entity as User;
